services:
  genesis:
    container_name: genesis
    image: ghcr.io/neodix42/mylocalton-docker:latest
    restart: unless-stopped
    ports:
      - 8000:8000         # simple file http server
      - 40004:40004       # lite-server
      - "40003:40003/udp" # dht-server
      - 40002:40002       # validator-console
      - "40001:40001/udp" # validator public port
    volumes:
      - shared-data:/usr/share/data
#      - /home/usr/ton-db:/var/ton-work/db # docker persistent storage for ton db
    environment:
      - GENESIS=true
      - NAME=genesis
#      - ENABLE_FILE_HTTP_SERVER=false #default true
#      - NEXT_BLOCK_GENERATION_DELAY=2 #default 2000 (2 seconds)
#      - EXTERNAL_IP= # used to generate  external.global.config.json that allows remote users to connect to lite-server via public IP
#      - VALIDATION_PERIOD=86400 # 24h, default 20min
#      - MASTERCHAIN_ONLY=true   # default false
#      - HIDE_PRIVATE_KEYS=true  # default false, defines whether to expose private keys  (faucet+validators) via htt-server on 127.0.0.1:8000 and generates new private keys for validators and faucets
#      - VERBOSITY=4
    healthcheck:
      test: /usr/local/bin/lite-client -a 127.0.0.1:40004 -b E7XwFSQzNkcRepUC23J2nRpASXpnsEKmyyHYV4u/FZY= -t 3 -c last
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      default:
        ipv4_address: 172.28.1.1

  blockchain-explorer:
    container_name: blockchain-explorer
    image: ghcr.io/neodix42/mylocalton-docker-explorer:latest
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    healthcheck:
      test: curl -sS http://127.0.0.1:8080/last || echo 1
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - shared-data:/usr/share/data
    depends_on:
      genesis:
        condition: service_healthy

#  validator-1:
#    container_name: validator-1
#    image: ghcr.io/neodix42/mylocalton-docker:latest
#    restart: unless-stopped
#    volumes:
#      - shared-data:/usr/share/data
#    environment:
#      - NAME=validator-1
#      - GENESIS_IP=172.28.1.1
#    depends_on:
#      - "genesis"
#
#  validator-2:
#    container_name: validator-2
#    image: ghcr.io/neodix42/mylocalton-docker:latest
#    restart: unless-stopped
#    volumes:
#      - shared-data:/usr/share/data
#    environment:
#      - NAME=validator-2
#      - GENESIS_IP=172.28.1.1
#    depends_on:
#      - "genesis"
#
#  validator-3:
#    container_name: validator-3
#    image: ghcr.io/neodix42/mylocalton-docker:latest
#    restart: unless-stopped
#    volumes:
#      - shared-data:/usr/share/data
#    environment:
#      - NAME=validator-3
#      - GENESIS_IP=172.28.1.1
#    depends_on:
#      - "genesis"
#
#  validator-4:
#    container_name: validator-4
#    image: ghcr.io/neodix42/mylocalton-docker:latest
#    restart: unless-stopped
#    volumes:
#      - shared-data:/usr/share/data
#    environment:
#      - NAME=validator-4
#      - GENESIS_IP=172.28.1.1
#    depends_on:
#      - "genesis"
#
#  validator-5:
#    container_name: validator-5
#    image: ghcr.io/neodix42/mylocalton-docker:latest
#    restart: unless-stopped
#    volumes:
#      - shared-data:/usr/share/data
#    environment:
#      - NAME=validator-5
#      - GENESIS_IP=172.28.1.1
#    depends_on:
#      - "genesis"

  tonhttpapi:
    container_name: ton-http-api
    image: ghcr.io/neodix42/ton-http-api:latest
    ports:
      - 8081:8081
    volumes:
      - shared-data:/usr/share/data
    environment:
      - TON_API_CACHE_ENABLED
      - TON_API_CACHE_REDIS_ENDPOINT
      - TON_API_CACHE_REDIS_PORT
      - TON_API_CACHE_REDIS_TIMEOUT
      - TON_API_LOGS_JSONIFY=0
      - TON_API_LOGS_LEVEL=ERROR
      - TON_API_TONLIB_LITESERVER_CONFIG=/usr/share/data/global.config.json
      - TON_API_TONLIB_KEYSTORE
      - TON_API_TONLIB_PARALLEL_REQUESTS_PER_LITESERVER
      - TON_API_TONLIB_CDLL_PATH=/usr/share/data/libtonlibjson.so
      - TON_API_TONLIB_REQUEST_TIMEOUT
      - TON_API_GET_METHODS_ENABLED=1
      - TON_API_JSON_RPC_ENABLED=1
    restart: unless-stopped
    depends_on:
      genesis:
        condition: service_healthy
    command: -c "gunicorn -k uvicorn.workers.UvicornWorker -w 1 --bind 0.0.0.0:8081 pyTON.main:app"
    healthcheck:
      test: curl -sS http://127.0.0.1:8081/healthcheck || echo 1
      interval: 30s
      timeout: 5s
      retries: 10

#  faucet:
#    container_name: faucet
#    image: ghcr.io/neodix42/mylocalton-docker-faucet:latest
#    ports:
#      - 88:88
#    volumes:
#      - shared-data:/usr/share/data
#    restart: unless-stopped
#    depends_on:
#      genesis:
#        condition: service_healthy
#    environment:
#      - RECAPTCHA_SITE_KEY= # google reCaptcha v2
#      - RECAPTCHA_SECRET=   # google reCaptcha v2
##      - MASTERCHAIN_ONLY=true   # default false, if true generates new addresses only in masterchain (-1)
##      - FAUCET_REQUEST_EXPIRATION_PERIOD=3600 #  default 86400 seconds (24h)
##      - FAUCET_SINGLE_GIVEAWAY=100    # default 10 toncoins
#      - SERVER_PORT=88             # default 80
#    healthcheck:
#      test: curl -sS http://127.0.0.1:88|| echo 1

volumes:
  shared-data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16