services:
  genesis:
    container_name: genesis
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000   # http
#      - 40001:40001 # node
#      - 40002:40002 # console
#      - "40003:40003/udp" # dht
#      - 40004:40004 # lite
#    volumes:
#      - ton:/var/ton-work/db
    environment:
      - GENESIS=true
      - PUBLIC_IP=172.28.1.1
    networks:
      default:
        ipv4_address: 172.28.1.1
  validator:
    container_name: validator
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "genesis"
    environment:
      - GENESIS=false
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
#volumes:
#  ton:
#    external: false