services:
  genesis:
    container_name: genesis
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000   # simple-http server
      - 8080:8080   # blockchain explorer
#    volumes:
#      - ton:/var/ton-work/db
    networks:
      default:
        ipv4_address: 172.28.1.1
  validator-1:
    container_name: validator-1
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "genesis"
    networks:
      default:
        ipv4_address: 172.28.1.10

  validator-2:
    container_name: validator-2
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "genesis"
    networks:
      default:
        ipv4_address: 172.28.1.20

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
#volumes:
#  ton:
#    external: false