services:
  genesis:
    container_name: genesis
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000   # simple-http server
      - 8080:8080   # blockchain explorer
#      - 9000:9000   # ton-http-api todo
      - 40004:40004 # lite-server
    environment:
      - GENESIS=true
      - NAME=genesis
    networks:
      default:
        ipv4_address: 172.28.1.1

  validator-1:
    container_name: validator-1
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENESIS=false
      - NAME=validator-1
      - GENESIS_IP=172.28.1.1
    depends_on:
      - "genesis"

  validator-2:
    container_name: validator-2
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENESIS=false
      - NAME=validator-2
      - GENESIS_IP=172.28.1.1
    depends_on:
      - "genesis"

  validator-3:
    container_name: validator-3
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENESIS=false
      - NAME=validator-3
      - GENESIS_IP=172.28.1.1
    depends_on:
      - "genesis"

  validator-4:
    container_name: validator-4
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENESIS=false
      - NAME=validator-4
      - GENESIS_IP=172.28.1.1
    depends_on:
      - "genesis"

  validator-5:
    container_name: validator-5
    image: mylocaltondocker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GENESIS=false
      - NAME=validator-5
      - GENESIS_IP=172.28.1.1
#      - VERBOSITY=4
    depends_on:
      - "genesis"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16